/**
 * Original 16×16 pixel-art chess sprites. Symmetrical pieces store only the
 * left 8 columns (mirrored when expanded); the knight is stored in full.
 * '#' outline, 'o' body fill, 'w' highlight/detail, '.' transparent.
 */
export type PieceType = "p" | "n" | "b" | "r" | "q" | "k";

const HALF: Record<Exclude<PieceType, "n">, string[]> = {
  p: [
    "........",
    "........",
    "......##",
    ".....#oo",
    "....#ooo",
    "....#owo",
    ".....#oo",
    "......##",
    ".....#oo",
    ".....#oo",
    "....#ooo",
    "...#oooo",
    "..#ooooo",
    ".#oooooo",
    ".#oooooo",
    ".#######",
  ],
  r: [
    "........",
    ".###.##.",
    ".#o###o#",
    ".#oooooo",
    ".######o",
    "..#owooo",
    "..#owooo",
    "..#owooo",
    "..#owooo",
    "..#owooo",
    "..######",
    ".#oooooo",
    ".#oooooo",
    ".#oooooo",
    ".#oooooo",
    ".#######",
  ],
  b: [
    "........",
    "......##",
    ".....#oo",
    "....#ooo",
    "...#owoo",
    "...#owoo",
    "...#oooo",
    "....#ooo",
    ".....#oo",
    "....#ooo",
    "..######",
    "...#oooo",
    "..#ooooo",
    ".#oooooo",
    ".#oooooo",
    ".#######",
  ],
  q: [
    "#..#..#.",
    "#.#o#.#.",
    "#oo#oo#o",
    ".#ooooo#",
    ".#oooooo",
    "..#owooo",
    "..#owooo",
    "..#oooo#",
    "..#ooooo",
    "..#oooo#",
    "..######",
    ".#oooooo",
    ".#oooooo",
    ".#oooooo",
    ".#oooooo",
    ".#######",
  ],
  k: [
    "......##",
    "......#o",
    "....####",
    "......#o",
    "..###.##",
    ".#oooo#o",
    ".#ooowoo",
    "..#ooooo",
    "..#owooo",
    "..#ooooo",
    "..######",
    ".#oooooo",
    ".#oooooo",
    ".#oooooo",
    ".#oooooo",
    ".#######",
  ],
};

const KNIGHT: string[] = [
  "................",
  "......##........",
  ".....#oo#.......",
  "....#ooo##......",
  "...#oooooo#.....",
  "..#owooooo#.....",
  "..#oo#oooooo#...",
  ".#oooooooooo#...",
  ".#oooo#.#ooo#...",
  "..###..#oooo#...",
  "......#ooooo#...",
  ".....#oooooo#...",
  "....#ooooooo#...",
  "...#oooooooo#...",
  "..#oooooooooo#..",
  "..############..",
];

function mirror(rows: string[]): string[] {
  return rows.map((r) => r + [...r].reverse().join(""));
}

export const SPRITES: Record<PieceType, string[]> = {
  p: mirror(HALF.p),
  n: KNIGHT,
  b: mirror(HALF.b),
  r: mirror(HALF.r),
  q: mirror(HALF.q),
  k: mirror(HALF.k),
};
